services:
  - type: web
    name: new-anal-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://new-anal-server.onrender.com/api/:splat
  - type: web
    name: new-anal-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: PGUSER
        value: your_user
      - key: PGHOST
        value: your_host
      - key: PGDATABASE
        value: your_database_name
      - key: PGPASSWORD
        value: your_password
      - key: PGPORT
        value: 5432
      - key: OPENAI_API_KEY
        value: your_openai_api_key
